### ISSUE TITLE
Remove Cognito docs from the Users folder and move to the IM Builder

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-learn-aws#18]
The Cognito documentation I added is better suited to live in the InfoMapper Builder docs, as its a bit more granular to that application. I have moved all necessary folders and files in the IM Builder, and everything in the `cognito/` folder under `users/` can be deleted.

**Comment by smalers** [comment]
I removed the files from the documentation.  Close this issue.
